language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-24
  - android-28
  - sys-img-armeabi-v7a-android-24

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - NODE_VERSION="12.13"
    - PATH=$JAVA_HOME/bin:$PATH

before_install:
  - yes | sdkmanager "platforms;android-29"

before_script:
  - nvm install $NODE_VERSION
  - npm install -g appium
#  - npm install appium-doctor -g
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - appium --log-level info > $HOME/appium_log.txt &
  - git clone https://github.com/ooni/probe-mobile-appium.git

script: 
#  - ./gradlew connectedAndroidTest
  - ./gradlew assembleDebug
#  - adb devices
#  - appium-doctor --android
  - ls  
  - ls /home/travis/app/build/outputs/apk/fdroid/debug/
  - cd probe-mobile-appium && gradle androidRegression
  - cat $HOME/appium_log.txt
  - cat /home/travis/build/ooni/probe-android/probe-mobile-appium/build/reports/tests/androidRegression/classes/probe.mobile.appium.runners.LandingPageRunner.html
