os: osx
osx_image: xcode11.2
env:
  global:
    - ANDROID_SDK_ROOT=$HOME/android-tools
    - NODE_VERSION="12.13"
    - PATH=${JAVA_HOME}/bin:PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$PATH

before_script:
  - sh scripts/install-android-tools.sh
  - sdkmanager --list
  - emulator -accel-check
  - nvm install $NODE_VERSION
  - npm install -g appium@1.16.0
  - npm install -g appium-doctor
  - make create-avd
  - emulator-headless -avd android-tablet &
  - adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'

script:
  - scripts/travis_appium_test.sh
