os: osx
osx_image: xcode8
env:
  global:
    - ANDROID_SDK_ROOT=$HOME/android-tools
    - NODE_VERSION="12.13"
    - PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$PATH
before_install:
  - "export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)"
  - "export PATH=${JAVA_HOME}/bin:$PATH"
install:
  - java -version
  - sh scripts/install-android-tools.sh
  - sdkmanager --list
  - nvm install $NODE_VERSION
  - npm install -g appium@1.16.0
  - npm install -g appium-doctor
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - scripts/travis_appium_test.sh
