# build checks whether the project builds
name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: checkout
      uses: actions/checkout@v2
    - run: ./gradlew clean && ./gradlew assembleDevFullRelease
    - name: uploads dev apk
      uses: actions/upload-artifact@v2
      with:
        name: dev-apk
        path: app/build/outputs/apk/devFull/release
