name: build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * */2"
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        version:
            - "StableFullRelease"
            - "StableFdroidRelease"
        api-level: [29]
        target: [google_apis]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ./gradlew build${{ matrix.version }} && ./gradlew clean
