# build checks whether the project builds
name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        version:
            - "StableFullRelease"
            - "StableFdroidRelease"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
       with:
        java-version: '11'
    - name: checkout
    - run: ./gradlew build${{ matrix.version }} && ./gradlew clean
