name: emulator
on:
  push:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [google_apis]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedStableFullDebugAndroidTest
