# test runs unit tests using the JVM
name: test
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: ./gradlew testStableFullRelease
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: uploads test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: app/build/test-results/testStableFullDebugUnitTest
