# test runs unit tests using the JVM
name: test
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: ./gradlew testStableFullRelease
